### ISSUE TITLE
Add console functionality

### ISSUE THREAD

**Issue by defkult** [SuperSpyTX/AntiBot#2]
I remote administrate my server from an IRC channel when I am away from my computer, the commands I run there are run as console, I cannot run the antibot commands from the IRC channel because of the limitation on where the commands are run from.  If you could add this, it would be great.  Thank you.

**Comment by SuperSpyTX** [comment]
I've actually silently implemented this option in one of my commits.

If you are willing to compile from source, the source code compiled version has this functionality.

If you need help compiling, i'll keep this issue open.

**Comment by defkult** [comment]
It's not an urgent issue.  I'll just wait for the next release.  I just wanted to get the functionality in there.  Thank you.

**Comment by SuperSpyTX** [comment]
Alrighty then.

Then it's ok for me to close this issue.

EDIT: I anticipate an update this weekend.
