### ISSUE TITLE
Couldn't pass PlayerKickEvent to AuthMe

### ISSUE THREAD

**Issue by defkult** [SuperSpyTX/AntiBot#3]
26.04 19:48:03 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=mp4t}
26.04 19:48:03 [Server] INFO     ... 25 more
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
26.04 19:48:03 [Server] INFO     at java.lang.reflect.Method.invoke(Method.java:601)
26.04 19:48:03 [Server] INFO     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.04 19:48:03 [Server] INFO     at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerQuit(AuthMePlayerListener.java:484)
26.04 19:48:03 [Server] INFO     at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:59)
26.04 19:48:03 [Server] INFO Caused by: java.lang.NullPointerException
26.04 19:48:03 [Server] INFO     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:61)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:48)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.Packet1Login.handle(SourceFile:68)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:94)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:129)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:132)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
26.04 19:48:03 [Server] INFO     at java.lang.reflect.Method.invoke(Method.java:601)
26.04 19:48:03 [Server] INFO     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.listeners.BotListener.onPlayerJoin(BotListener.java:73)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.handlers.BotHandler.onPlayerJoin(BotHandler.java:121)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.datatrack.BotDataTrack.trackPlayer(BotDataTrack.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.craftbukkit.entity.CraftPlayer.kickPlayer(CraftPlayer.java:220)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetServerHandler.disconnect(NetServerHandler.java:158)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:179)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
26.04 19:48:03 [Server] INFO org.bukkit.event.EventException
26.04 19:48:03 [Server] SEVERE Could not pass event PlayerQuitEvent to AuthMe
26.04 19:48:03 [Server] INFO     ... 24 more
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
26.04 19:48:03 [Server] INFO     at java.lang.reflect.Method.invoke(Method.java:601)
26.04 19:48:03 [Server] INFO     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.04 19:48:03 [Server] INFO     at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerKick(AuthMePlayerListener.java:524)
26.04 19:48:03 [Server] INFO     at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:59)
26.04 19:48:03 [Server] INFO Caused by: java.lang.NullPointerException
26.04 19:48:03 [Server] INFO     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:61)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:48)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.Packet1Login.handle(SourceFile:68)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:94)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:129)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:132)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
26.04 19:48:03 [Server] INFO     at java.lang.reflect.Method.invoke(Method.java:601)
26.04 19:48:03 [Server] INFO     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
26.04 19:48:03 [Server] INFO     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.listeners.BotListener.onPlayerJoin(BotListener.java:73)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.handlers.BotHandler.onPlayerJoin(BotHandler.java:121)
26.04 19:48:03 [Server] INFO     at somebody.is.madbro.datatrack.BotDataTrack.trackPlayer(BotDataTrack.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.craftbukkit.entity.CraftPlayer.kickPlayer(CraftPlayer.java:220)
26.04 19:48:03 [Server] INFO     at net.minecraft.server.NetServerHandler.disconnect(NetServerHandler.java:136)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
26.04 19:48:03 [Server] INFO     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
26.04 19:48:03 [Server] INFO org.bukkit.event.EventException
26.04 19:48:03 [Server] SEVERE Could not pass event PlayerKickEvent to AuthMe
26.04 19:48:03 [Server] INFO [§SkyNet] has detected multiple accounts!!
26.04 19:48:03 [Multicraft] mp4t ran command Message of the Day
26.04 19:48:03 [Connect] User mp4t, IP <snip>

**Comment by SuperSpyTX** [comment]
Restart your server.

Or remove the plugin.  Also, you have your player's IP in there.

Please make a issue with the author's ticketing system.  Because AntiBot isn't the problem.  It's a conflict with the other.

**Comment by defkult** [comment]
Apologies.  Couldn't tell if it was this plugin or the other one.  Thanks for catching the IP as well.
