### ISSUE TITLE
Spam Check deactivated?

### ISSUE THREAD

**Issue by DeathShadow** [SuperSpyTX/AntiBot#4]
06:45:45 [INFO] [AntiBot] Enabling AntiBot v2.7.1
**06:45:45 [INFO] AntiBot: Attempt to do the impossible - Eminem.
06:45:45 [WARNING] [AC] The SPAM check was deactivated.**
06:45:45 [INFO] AntiBot: Configuration Loaded Successfully!
06:45:45 [INFO] Loading GeoIP..
06:45:45 [INFO] AntiBot version 2.7.1 is enabled!
06:45:45 [INFO] If you have any issues with AntiBot.  Or there is a false positive! Don't be afraid to make a ticket!

**Comment by SuperSpyTX** [comment]
Alrighty then, let's play I Spy.

What do you see in this picture?
http://my.mn.vc/2x132z42093J2f0x1r3z

Meh screw it.

But seriously though, did you look at the changelogs in regards to the update? AntiBot disables the spam check on startup & reload if the anti spam configuration option is enabled.
