### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Xarc-zz** [SuperSpyTX/AntiBot#5]
I don't know if this error is from AntiBot or from STAB http://pastebin.com/xavaFB9E
I will post to STAB developer too.

**Comment by SuperSpyTX** [comment]
Exceptions don't help me without context.

Please explain what's happening here.  I've read the Exception and it's AntiBot.

I'm also confused why you would run STAB alongside with AntiBot when AntiBot has some of the same features as STAB.
