### ISSUE TITLE
Hi i have one problem on antibot 4.0

### ISSUE THREAD

**Issue by Baris2689** [SuperSpyTX/AntiBot#8]
http://puu.sh/1q8qL

i can't understand this problem

writing here Eminem what is this ?

and how can i fix it ? 

thanks for help.

**Comment by SuperSpyTX** [comment]
Sounds like a configuration problem on my end.

AntiBot 4.0 is still currently under development and should not be used for live testing at all.  Not even the configuration is finished.

Right now, AntiBot is under hiatus until I can grab my newer code from my Mac Pro, which won't be for a (really) good amount of time.

Until then, I cannot fix this issue currently.

For now, use a different plugin until this one is officially supported.

**Comment by Baris2689** [comment]
thx
